on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: lyra95
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          bash build-and-push.sh