name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-push-bitnami:
    strategy:
      matrix:
        image:
          [
            { base: bitnami/postgresql, tag: latest },
            { base: bitnami/postgresql, tag: 14 },
            { base: bitnami/postgresql, tag: 14.5.0 },
          ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: lyra95
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: set-env
        run: |
          BASE=${{ matrix.image.base }}
          TAG=${{ matrix.image.tag }}
          NEW_TAG=$(echo "$BASE-$TAG" | sed -E 's/[^A-Za-z0-9_.-]/-/g')
          echo "BASE=$BASE" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
      - run: |
          make -e build
          make -e push
  build-and-push-official:
    strategy:
      matrix:
        image:
          [
            { base: postgres, tag: bullseye },
            { base: postgres, tag: 14-bullseye },
            { base: postgres, tag: 14.5-bullseye },
          ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: lyra95
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: set-env
        run: |
          BASE=${{ matrix.image.base }}
          TAG=${{ matrix.image.tag }}
          NEW_TAG=$(echo "$BASE-$TAG" | sed -E 's/[^A-Za-z0-9_.-]/-/g')
          POSTGRESQL_BUILD_PKG_VERSION=$(echo $TAG | sed -E 's/([0-9]*).*/\1/g')
          echo "BASE=$BASE" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "POSTGRESQL_BUILD_PKG_VERSION=${POSTGRESQL_BUILD_PKG_VERSION:-all}" >> $GITHUB_ENV
      - run: |
          make -e build
          make -e push
